#!/usr/bin/env python3
"""Convert a permissively licensed mesh into a compact StoryVoxel C++ header.

Requires: trimesh (https://github.com/mikedh/trimesh)

This tool deliberately runs offline. It never downloads an asset or changes its
licence metadata: provide the original asset locally, retain its attribution,
and record the source in the generated header or ASSET_MANIFEST.md.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import trimesh


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Voxelise OBJ/GLB/PLY/STL meshes into flash-resident StoryVoxel headers."
    )
    parser.add_argument("input", type=Path, help="Permissively licensed local mesh asset")
    parser.add_argument("output", type=Path, help="Generated .h file")
    parser.add_argument("--name", default="IMPORTED_WORLD", help="C++ asset identifier")
    parser.add_argument("--palette", type=int, default=6, choices=range(8), help="Palette index 0..7")
    parser.add_argument("--resolution", type=int, default=48, help="Longest mesh axis in output voxels")
    parser.add_argument("--max-voxels", type=int, default=24000, help="Safety ceiling for generated points")
    parser.add_argument("--source", default="", help="Required human-readable licence/source attribution")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.input.exists():
        raise SystemExit(f"Input mesh not found: {args.input}")
    if args.resolution < 4:
        raise SystemExit("--resolution must be at least 4")

    mesh = trimesh.load(args.input, force="mesh", process=True)
    if mesh.is_empty:
        raise SystemExit("Input contained no mesh geometry")

    # Fit the longest dimension into the requested voxel resolution, then fill
    # a watertight volume where possible. The resulting grid lives only in the
    # desktop conversion process; the ESP32 receives the compact point list.
    extent = float(max(mesh.extents))
    if extent <= 0.0:
        raise SystemExit("Input mesh has zero extent")
    pitch = extent / float(args.resolution - 1)
    voxel_grid = mesh.voxelized(pitch).fill()
    points = voxel_grid.points
    if len(points) > args.max_voxels:
        raise SystemExit(
            f"Voxel result has {len(points)} points, exceeding --max-voxels {args.max_voxels}. "
            "Lower --resolution or raise the ceiling deliberately."
        )

    # Centre all coordinates around origin and keep each within signed int8.
    minimum = points.min(axis=0)
    maximum = points.max(axis=0)
    centre = (minimum + maximum) * 0.5
    integer_points = []
    for point in points:
        x, y, z = (round(float(v)) for v in point - centre)
        if not (-127 <= x <= 127 and -127 <= y <= 127 and -127 <= z <= 127):
            raise SystemExit("Centered coordinates exceed StoryVoxel int8 range")
        integer_points.append((x, y, z))
    integer_points.sort(key=lambda item: (item[2], item[1], item[0]))

    name = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in args.name.upper())
    attribution = args.source or "SOURCE / LICENCE: RECORD BEFORE DISTRIBUTION"
    lines = [
        "#pragma once",
        "",
        f"// Generated by tools/mesh_to_storyvoxels.py from {args.input.name}",
        f"// {attribution}",
        f"const StoryVoxel {name}[] PROGMEM = {{",
    ]
    lines.extend(f"  {{{x}, {y}, {z}, {args.palette}}}," for x, y, z in integer_points)
    lines.extend(
        [
            "};",
            f"constexpr uint16_t {name}_COUNT = sizeof({name}) / sizeof({name}[0]);",
            "",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(integer_points)} flash-resident voxels to {args.output}")


if __name__ == "__main__":
    main()
